GET http://localhost:3000

### Get all users
GET http://localhost:3000/api/users

### Single user
GET http://localhost:3000/api/users/1
###Get all books
GET http://localhost:3000/api/books
###POST all books
POST http://localhost:3000/api/books
Content-Type: application/application/json

{
  "title": "Book 1",
    "year": 2021,
    "isPublished": true,
    "category": "Fiction"
}

### get single book

GET http://localhost:3000/api/books/2
###Get all people
GET http://localhost:3000/api/people

### get married persons

GET http://localhost:3000/api/people/married
### get salary

GET http://localhost:3000/api/people/salary/avg
